## Basic Configuration

baseurl = "https://main.d2lcwferahffgb.amplifyapp.com/"
builddrafts = false
canonifyurls = false
languageCode = "en-US"

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

author = "Ronnie Eichler"
title = "Ronnie Eichler"

theme = "hugo-goa"

## Hugo Built-in Features
#disqusShortname = "https-shenoybr-github-io-hugo-goa-demo" # Comment out to disable Disqus.
#googleAnalytics = "XYZ"
enableRobotsTXT = true

## Site Settings
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[permalinks]
  posts = '/:title/'

[params]
author = "Ronnie Eichler"
intro = "Technology. Photography. Travel."
description = "Senior Global Solutions Architect at AWS. <br/> All opinions are my own and not those of my employer."
authorimage = "headshot.jpg"
dateformat = "Jan 2, 2006"

## Site Meta Settings
[params.meta]
description = "Ronnie Eichler"
keywords = "blog,hugo,developer,technology,photography,travel"

## Social Accounts
[params.social]
github = "ranrotx"
instagram = "ronnie.eichler"
linkedin = "ronnieeichler"
twitter = "ronnieeichler"
#facebook = "<username>"
#google = "<username>"
#stackoverflow = "<username>"
email = "ronnie@ronnieeichler.com"

## Extras
[params.extra]
copyright = "© 2021, Ronnie Eichler. [Some Rights Reserved](http://creativecommons.org/licenses/by/3.0/)." 
poweredby = false
hightlightjs = true

## Main Menu
[[menu.main]]
    name = "blog"
    weight = 100
    identifier = "blog"
    url = "/posts/"
[[menu.main]]
    name = "about"
    identifier = "about"
    weight = 200
    url = "/about/"
